"use client";

import Link from "next/link";

const PLANS = [
  {
      id: "free",
          name: "Free",
              price: "2,89 €",
                  period: "/mois",
                      description: "Pour tester la magie du drama.",
                          stripeUrl: "https://buy.stripe.com/3cIdRbgoi8U6c926pJeEo03",
                              features: [
                                    "5 générations de scripts / mois",
                                          "Vidéos avec watermark",
                                                "Qualité standard 720p",
                                                    ],
                                                        buttonText: "Commencer gratuitement",
                                                            highlighted: false,
                                                              },
                                                                {
                                                                    id: "pro",
                                                                        name: "Pro",
                                                                            price: "14,99 €",
                                                                                period: "/mois",
                                                                                    description: "Pour les créateurs réguliers qui veulent performer.",
                                                                                        stripeUrl: "https://buy.stripe.com/dRm28tc827Q2fle9BVeEo02",
                                                                                            features: [
                                                                                                  "Générations illimitées",
                                                                                                        "Sans watermark",
                                                                                                              "Qualité HD 1080p",
                                                                                                                    "Voix storytelling premium",
                                                                                                                        ],
                                                                                                                            buttonText: "Passer Pro",
                                                                                                                                highlighted: true,
                                                                                                                                  },
                                                                                                                                    {
                                                                                                                                        id: "business",
                                                                                                                                            name: "Business",
                                                                                                                                                price: "20 €",
                                                                                                                                                    period: "/mois",
                                                                                                                                                        description: "Pour les agences et les studios.",
                                                                                                                                                            stripeUrl: "https://buy.stripe.com/aFa14pb3Y6LY7SM9BVeEo01",
                                                                                                                                                                features: [
                                                                                                                                                                      "Tout le plan Pro",
                                                                                                                                                                            "Accès API complet",
                                                                                                                                                                                  "Bot d'automatisation 24/7",
                                                                                                                                                                                        "Support prioritaire",
                                                                                                                                                                                            ],
                                                                                                                                                                                                buttonText: "Contacter les ventes",
                                                                                                                                                                                                    highlighted: false,
                                                                                                                                                                                                      },
                                                                                                                                                                                                      ];

                                                                                                                                                                                                      export function PricingCards() {
                                                                                                                                                                                                        return (
                                                                                                                                                                                                            <div className="grid md:grid-cols-3 gap-8 max-w-6xl mx-auto px-4">
                                                                                                                                                                                                                  {PLANS.map((plan) => (
                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                    key={plan.id}
                                                                                                                                                                                                                                              className={`flex flex-col justify-between p-6 rounded-2xl border transition-all ${
                                                                                                                                                                                                                                                          plan.highlighted
                                                                                                                                                                                                                                                                        ? "border-red-500 bg-zinc-900/80 shadow-lg shadow-red-500/10 scale-105"
                                                                                                                                                                                                                                                                                      : "border-zinc-800 bg-zinc-900/40"
                                                                                                                                                                                                                                                                                                }`}
                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                              <h3 className="text-xl font-bold text-white">{plan.name}</h3>
                                                                                                                                                                                                                                                                                                                                          <p className="text-sm text-zinc-400 mt-1">{plan.description}</p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                  <div className="mt-4 flex items-baseline">
                                                                                                                                                                                                                                                                                                                                                                                <span className="text-3xl font-extrabold text-white">{plan.price}</span>
                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-zinc-400 text-sm ml-1">{plan.period}</span>
                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                      <ul className="mt-6 space-y-3 text-sm text-zinc-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                    {plan.features.map((feature, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <li key={i} className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-red-500 font-bold">✓</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {feature}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href={plan.stripeUrl}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className={`w-full block text-center mt-8 py-2.5 rounded-lg font-medium transition-colors ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    plan.highlighted
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? "bg-red-600 hover:bg-red-700 text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : "bg-zinc-800 hover:bg-zinc-700 text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {plan.buttonText}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    